### ISSUE TITLE
NoClassDefFoundError - TrustStrategy

### ISSUE THREAD

**Issue by llowinge** [xtf-cz/xtf#102]
I'm getting with 0.9-SNAPSHOT
`java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cz.xtf.openshift.OpenShiftBinaryClient.getBinary(OpenShiftBinaryClient.java:208)
	at cz.xtf.openshift.OpenShiftBinaryClient.<init>(OpenShiftBinaryClient.java:34)
	at cz.xtf.openshift.OpenShiftBinaryClient.getInstance(OpenShiftBinaryClient.java:40)`

**Comment by Crumby** [comment]
@llowinge What are you exactly trying to do? Project compiles without problem, also class loading works fine for me as for external usage... Maybe this got something to do with recent update httpclient component udpate from 4.3.6 to 4.5.5?

**Comment by llowinge** [comment]
@Crumby In testsuite i call `final String result = OpenShiftBinaryClient.getInstance().executeCommandWithReturn("failure calling "
				+ "oc new-app --template=decisionserver64-basic-s2i", "new-app", "-n", OpenshiftUtil.getInstance().getContext().getNamespace(), "--template=decisionserver64-basic-s2i", "-p", "KIE_CONTAINER_DEPLOYMENT=decisionserver-hellorules=org.openshift.quickstarts:decisionserver-hellorules:1.4.0.Final");`

**Comment by llowinge** [comment]
@Crumby I found that if i add 
`		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.9</version>
		</dependency>`
Then it works.

**Comment by Crumby** [comment]
@llowinge So this one can be closed, I guess.

**Comment by llowinge** [comment]
@Crumby yes
