### ISSUE TITLE
Race condition between multiple build creations

### ISSUE THREAD

**Issue by llowinge** [xtf-cz/xtf#113]
When multiple testsuites are containing the same @UsesFuseBuild (eg. JDBC_KARAF) then this error can happen

```
com.redhat.xpaas.OthersFuseTestSuite  Time elapsed: 21.747 sec  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.foo39.dos.fuse-qe.eng.rdu2.redhat.com:8443/apis/image.openshift.io/v1/namespaces/xpaasqe-builds/imagestreams. Message: imagestreams.image.openshift.io "camel-jdbc-fuse-karaf" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=image.openshift.io, kind=imagestreams, name=camel-jdbc-fuse-karaf, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=imagestreams.image.openshift.io "camel-jdbc-fuse-karaf" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:773)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	at cz.xtf.openshift.OpenshiftUtil.lambda$createImageStream$9(OpenshiftUtil.java:294)
	at cz.xtf.openshift.OpenshiftUtil.withDefaultUser(OpenshiftUtil.java:177)
	at cz.xtf.openshift.OpenshiftUtil.createImageStream(OpenshiftUtil.java:293)
	at cz.xtf.build.BuildProcess.deployResources(BuildProcess.java:70)
	at cz.xtf.build.BuildProcess.deployBuildFromGit(BuildProcess.java:63)
	at cz.xtf.build.BuildProcess.deployBuildFromGit(BuildProcess.java:56)
	at cz.xtf.build.PathGitBuildProcess.deployBuild(PathGitBuildProcess.java:34)
	at cz.xtf.build.BuildManagerV2.deployBuild(BuildManagerV2.java:66)
	at cz.xtf.build.BuildManagerV2.lambda$deployBuilds$0(BuildManagerV2.java:86)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cz.xtf.build.BuildManagerV2.deployBuilds(BuildManagerV2.java:86)
	at cz.xtf.junit.XTFTestSuite.deployBuilds(XTFTestSuite.java:227)
	at cz.xtf.junit.XTFTestSuite.beforeSuite(XTFTestSuite.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by Crumby** [comment]
@llowinge Take a look at https://github.com/xtf-cz/xtf/pull/114. Might help to solve your problem.

**Comment by llowinge** [comment]
@Crumby looks great ! especially the check for deleted build resources

**Comment by llowinge** [comment]
@Crumby I will close it, re-open when i will see it again.
