### ISSUE TITLE
ClusterVersionInfo doesn't work well with nightly builds of OCP

### ISSUE THREAD

**Issue by simkam** [xtf-cz/xtf#491]
[cz.xtf.core.openshift.ClusterVersionInfo](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java)

```
Server Version: 4.11.0-0.nightly-2022-05-25-193227
```

```
Caused by: java.lang.IllegalStateException: No match found
        at java.base/java.util.regex.Matcher.group(Matcher.java:645)
        at cz.xtf.core.openshift.ClusterVersionInfo.isMajorMinorMicro(ClusterVersionInfo.java:72)
        at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.getVersionOrChannel(ClusterVersionOpenShiftBinaryPathResolver.java:228)
        at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.getClientUrlBasedOnOcpVersion(ClusterVersionOpenShiftBinaryPathResolver.java:84)
        at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.determineClientUrl(ClusterVersionOpenShiftBinaryPathResolver.java:42)
        at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.resolve(ClusterVersionOpenShiftBinaryPathResolver.java:32)
        at cz.xtf.core.openshift.OpenShiftBinaryManagerFactory.getOpenShiftBinaryManager(OpenShiftBinaryManagerFactory.java:19)
        at cz.xtf.core.openshift.OpenShifts.getBinaryPath(OpenShifts.java:83)
        at com.redhat.xpaas.eap.util.OpenShiftBinaryClient.<init>(OpenShiftBinaryClient.java:26)
        at com.redhat.xpaas.eap.util.OpenShiftBinaryClient.getInstance(OpenShiftBinaryClient.java:32)
        at com.redhat.xpaas.eap.operator.junit.listener.OperatorInstaller.installOperator(OperatorInstaller.java:544)
        at com.redhat.xpaas.eap.operator.junit.listener.OperatorInstaller.testPlanExecutionStarted(OperatorInstaller.java:126)
        ... 19 more
```

**Comment by mchoma** [comment]
Could we have a fix please as OCP 4.11 is approaching. CC : @mnovak1

**Comment by simkam** [comment]
There is no issue with 4.11, only with nightly builds. As far as I know, it doesn't break anything. `oc` binary is downloaded directly from cluster when version is not recognized. Workaround to get rid of exception from logs is to set version in config to some existing release, e.g. `xtf.openshift.version=4.10.16`.

**Comment by mchoma** [comment]
Operator is not installed in my case:

```
[2022-06-14 12:41:28,535] ERROR- Failed to install operator
java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.group(Matcher.java:645)
	at cz.xtf.core.openshift.ClusterVersionInfo.isMajorMinorMicro(ClusterVersionInfo.java:72)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.getVersionOrChannel(ClusterVersionOpenShiftBinaryPathResolver.java:228)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.getClientUrlBasedOnOcpVersion(ClusterVersionOpenShiftBinaryPathResolver.java:84)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.determineClientUrl(ClusterVersionOpenShiftBinaryPathResolver.java:42)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.resolve(ClusterVersionOpenShiftBinaryPathResolver.java:32)
	at cz.xtf.core.openshift.OpenShiftBinaryManagerFactory.getOpenShiftBinaryManager(OpenShiftBinaryManagerFactory.java:19)
	at cz.xtf.core.openshift.OpenShifts.getBinaryPath(OpenShifts.java:83)
	at com.redhat.xpaas.eap.util.OpenShiftBinaryClient.<init>(OpenShiftBinaryClient.java:26)
	at com.redhat.xpaas.eap.util.OpenShiftBinaryClient.getInstance(OpenShiftBinaryClient.java:32)
	at com.redhat.xpaas.eap.operator.junit.listener.OperatorInstaller.installOperator(OperatorInstaller.java:544)
	at com.redhat.xpaas.eap.operator.junit.listener.OperatorInstaller.testPlanExecutionStarted(OperatorInstaller.java:126)
```

**Comment by mchoma** [comment]
>  Workaround ... is to set version in config to some existing release, e.g. xtf.openshift.version=4.10.16

I can confirm it works for me.
