### ISSUE TITLE
ClusterVersionOpenShiftBinaryPathResolverTest failing because of changed oc location

### ISSUE THREAD

**Issue by simkam** [xtf-cz/xtf#566]
It looks like nightly builds are no longer pushed to https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp-dev-preview/. At least version `4.14.0-ec.1`, that we use in test, is not there and resolver than fallbacks to `stable` stable channel which obviously is in `ocp-dev-preview`.

```
Error:  cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolverTest.resolveTest(String, String, String)[3]  Time elapsed: 0.905 s  <<< ERROR!
java.lang.IllegalStateException: Failed to download and extract oc binary from https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp-dev-preview/stable/openshift-client-linux.tar.gz
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolverTest.testDownloadedVersion(ClusterVersionOpenShiftBinaryPathResolverTest.java:68)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolverTest.resolveTest(ClusterVersionOpenShiftBinaryPathResolverTest.java:50)
Caused by: java.io.FileNotFoundException: https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp-dev-preview/stable/openshift-client-linux.tar.gz
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolverTest.testDownloadedVersion(ClusterVersionOpenShiftBinaryPathResolverTest.java:68)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolverTest.resolveTest(ClusterVersionOpenShiftBinaryPathResolverTest.java:50)
```

**Comment by simkam** [comment]
It looks like currently ec builds are in `candidates-` folders (https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp-dev-preview/candidate-4.16/) and nightly builds only in https://amd64.ocp.releases.ci.openshift.org/.
