### ISSUE TITLE
mcr.microsoft.com/mssql/rhel/server:2022-CU13-rhel-9.1 should have one or two '/' 

### ISSUE THREAD

**Issue by mchoma** [xtf-cz/xtf#572]
XTF does not allow for me to use image like `mcr.microsoft.com/mssql/rhel/server:2022-CU13-rhel-9.1`

```
java.lang.IllegalArgumentException: image 'mcr.microsoft.com/mssql/rhel/server:2022-CU13-rhel-9.1' should have one or two '/' characters
	at cz.xtf.core.image.Image.from(Image.java:71)
	at cz.xtf.core.image.Image.get(Image.java:18)
	at cz.xtf.core.image.Image.resolve(Image.java:22)
	at cz.xtf.builder.db.MsSQL.getImageName(MsSQL.java:113)
	at cz.xtf.builder.db.AbstractDatabase.configureDeployment(AbstractDatabase.java:186)
	at cz.xtf.builder.db.AbstractDatabase.configureDeployment(AbstractDatabase.java:181)
```

We need `case 4+: ` section here? 

https://github.com/xtf-cz/xtf/blob/1daa976b2e32c0bc9fcdfda1ae947d37836c15fa/core/src/main/java/cz/xtf/core/image/Image.java#L54-L71

So we will end up with something like this
```
registry = mcr.microsoft.com
user = mssql/rhel
repoTag = server:2022-CU13-rhel-9.1
```

**Comment by mchoma** [comment]
@dosu what do you think?

**Comment by mchoma** [comment]
@dosu any objection with linked pull request? Do you think it address original issue? Are linked tests correctly testing change?

**Comment by mchoma** [comment]
@dosu No that check is not implemented in https://github.com/xtf-cz/xtf/pull/577/
